### ISSUE TITLE
Unable to deploy apps!

### ISSUE THREAD

**Issue by sixshooterz** [PTS-Team/Apps-Community#10]
Trying to deploy apps from the Community Box and get the error below. Happened with Heimdall and Piwigo. Please help!
`TASK [Script Execute Part I] ***************************************************
Friday 17 January 2020  21:09:52 -0500 (0:00:00.232)       0:00:06.012 ********
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "bash /opt/plexguide/menu/shield/drop.sh", "delta": "0:00:00.005011", "end": "2020-01-17 21:09:52.652418", "msg": "non-zero return code", "rc": 127, "start": "2020-01-17 21:09:52.647407", "stderr": "bash: /opt/plexguide/menu/shield/drop.sh: No such file or directory", "stderr_lines": ["bash: /opt/plexguide/menu/shield/drop.sh: No such file or directory"], "stdout": "", "stdout_lines": []}
`

**Comment by justinglock40** [comment]
Are you on the right project as piwigo is not available on our setup?

**Comment by sixshooterz** [comment]
I'm positive, it sure as hell shows up on the install options! Maybe it's a relic from the pg days? Either way, I tried ZeroTier and other apps and get the same error. Is it because I refuse to use the shield feature? That's never been an issue before.

Why close the issue before I have a chance to respond? Smh

**Comment by justinglock40** [comment]
Make sure you followed the install wiki correctly and also run 'sudo ptsupdate' and try again

**Comment by sixshooterz** [comment]
ptsupdate was the first thing I did. I've been running pts since it was forked and, with the exception of a few Traefik issues quickly resolved by MrDoob, I've not had any issues.

I'm looking for the file it's referencing, /opt/plexguide/menu/shield/drop.sh and it doesn't exist. The entire shield folder is missing.

I just tried ptsupdate again and the following error is received along the way. 

`TASK [Installing Version master] ***********************************************
Saturday 18 January 2020  09:25:41 -0500 (0:00:00.229)       0:00:01.166 ******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://github.com/PTS-Team/PTS-Team /opt/plexguide", "msg": "fatal: destination path '/opt/plexguide' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/opt/plexguide' already exists and is not an empty directory.\n", "stderr_lines": ["fatal: destination path '/opt/plexguide' already exists and is not an empty directory."], "stdout": "", "stdout_lines": []}
...ignoring`

**Comment by sixshooterz** [comment]
If I remove /opt/plexguide and re-run ptsupdate, is that going to mess up my install?

**Comment by MrDoobPG** [comment]
`
past this command ...

sudo rm -rf /opt/plexguide && sudo git clone https://github.com/PTS-Team/PTS-Team.git /opt/plexguide  && sudo chown -cR 1000:1000 /opt/plexguide && sudo chmod -cR 775 /opt/plexguide && sudo ptsupdate

`

**Comment by sixshooterz** [comment]
MrDoob, once again you come to the rescue! That seems to have fixed it! I'm not sure why my ptsupdate stopped working but everything is good again.
